project:
  type: book

format:
  html: default
  pdf: default

book:
  title: "Field Guide to Relational and Systems Epidemiology"
  author: "Jon Zelner"
  date: "9/8/2023"
  chapters:
    - part: Introduction
      chapters:
        - index.qmd
        - invitation.qmd
        - elements.qmd
        - laws.qmd
        - relationships.qmd
    - part: Residential Segregation
      chapters: 
        - segregation/index.qmd
    - part: Environmental Exposure
      chapters:
        - smoothing.qmd
        - density.qmd
        - radon-multilevel.qmd
        - spatial-radon.qmd



number-depth: 2
bibliography: contextual-epi.bib
csl: american-journal-of-epidemiology.csl
execute:
  cache: true