project:
  type: book

format:
  html: default
  pdf: default

book:
  title: "Field Guide of Contextual and Relational Epidemiology"
  author: "Jon Zelner"
  date: "9/8/2023"
  chapters:
    - part: Introduction
      chapters:
        - index.qmd
        - invitation.qmd
    - part: relationships.qmd
      chapters:
        - space.qmd
        - time.qmd
        - people.qmd
  

number-depth: 1
bibliography: contextual-epi.bib
csl: american-journal-of-epidemiology.csl
