project:
  type: book

book:
  title: "Field Guide of Contextual and Relational Epidemiology"
  author: "Jon Zelner"
  date: "9/8/2023"
  chapters:
    - index.qmd
    - invitation.qmd


bibliography: contextual-epi.bib

  