---
title: "Relationships"
format: html
---

## Spatial Epidemiology is All About Relationships

The focus of this class session will be on understanding the concept of spatial *autocorrelation* and *variation* and what they means for epidemiological analysis. Where *variation* is large, we should expect to see big differences from place to place. 

Autocorrelation is about how that variation plays out over space: Where there is strong spatial autocorrelation, things that are close to each other are far more likely to be similar than things that are far away from each other. But one can have strong autocorrelation and low variation, high variation and no autocorrelation, and on and on...

We will spend this class session trying to make sense of this concept in qualitative terms, first by discussing a pair of articles that nicely lay out the key ideas here, and then by doing a hands-on activity focused on visualizing patterns of spatial variation and autocorrelation using a *spatial smoothing* approach.

### Additional Resources 

Please read the following two pieces that discuss key ideas about geospatial relatedness:

Miller HJ. Tobler’s First Law and Spatial Analysis. _Annals of the Association of American Geographers_. 2004;94(2):284-289. doi:[10.1111/j.1467-8306.2004.09402005.x](https://doi.org/10.1111/j.1467-8306.2004.09402005.x)

Goodchild MF. The Validity and Usefulness of Laws in Geographic Information Science and Geography. _Annals of the Association of American Geographers_. 2004;94(2):300-303. doi:[10.1111/j.1467-8306.2004.09402008.x](https://doi.org/10.1111/j.1467-8306.2004.09402008.x)